
spring:
  messages:
    basename: i18n/messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pms?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 10
      max-total: 10
      max-wait-millis: 2000
    filters: stat,wall
mybatis:
  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: com.yn.pms.entity
  mapper-locations:
  - classpath:mapper/**/*.xml
logging:
  level:
    com.yn.pms.dao: debug


server:
  port: 9999


